### PR TITLE
Added Omenad Bangla Font for Indian Music

### PR DESCRIPTION
**Pull request by jain-sanjay**
Bangla .sfd generated and uploaded.
Also upploaded the Documentation

### CODE REVIEW

**Comment by rajadain** [comment]
I’ve added a few changes to get this to build correctly. On initiali observation it seems like there’s a number of spacing issues, where the necessary width of 1582 is not applied:

image

That monospacing of each glyph to 1582 allows all the characters to line up. I’ll see if I can spend some time on this in the next week to get the spacing right.

Where did you source the glyphs from?

**Comment by jain-sanjay** [comment]
Hi Terence
Thank you for your review and comments. As you can probably tell , I am a
novice at this.
I sourced the Glyphs from an Open Source Bangla Fonts project called Akaash
https://www.nongnu.org/freebangfont/downloads.html

Thanks

Sanjay

**Comment by jain-sanjay** [comment]
Hi Terence

Checking to see how to advance this further. Should I try to re-do the
Bengali Map?

Also , there is one request- For all Omenad fonts-- There is no symbol
designated for 'Chikari'. This is the strike of the drone strings and is
used  often in Sitar. We usually use Dollar sign for it.

Thanks

Sanjay

**Comment by rajadain** [comment]
Hi Sanjay,

Sorry for the delay, I'm going to take a look at this soon. I will ask questions regarding the Bangla characters if needed.

We have #64 for the Chikari request. If you have any sketches or screenshots of compositions where you use that symbol, please add them there.

On another note, would you be interested in translating the documentation into Bangla? Do you think that would help make this more accessible to Bangla speakers?

Thanks.

**Comment by jain-sanjay** [comment]
Sure, l can do the translation. That will be definitely helpful

Let me get back to you regarding the Symbol for Chikari

**Comment by rajadain** [comment]
Hi Sanjay,

After putting some more thought into this, I've realized that the best way forward is to create a build pipeline that takes the musical Bhatkhande symbols and combines it with different languages to make the final files, rather than to have separate files for each font, which isn't sustainable. I've created #66 for that refactor. Will work on that first, then will add in the Bangla font.

I've created #67 for requesting translations for the docs. If you are still inclined to do it, please open a separate pull request for that.

Thank you!

**Comment by jain-sanjay** [comment]
Great thought Terence!

Will you be working to enable to Bangla Font as per new approach?
I will be happy to work on Transalation and start soon

Thanks

Sanjay

**Comment by rajadain** [comment]
Yes that's the plan. Thanks to your work above, and the link to the Bangla source, I'll add that in once the new build pipeline is ready.

My aim is to have this ready in the next 2 weeks.

**Comment by jain-sanjay** [comment]
Hi Terence

Wanted to check on the latest on this. I am hoping to present this as a
Birthday Gift to my Guru by end of August



Sanjay

**Comment by rajadain** [comment]
Thanks for checking in Sanjay. Unfortunately as I've been working on #66 I've discovered additional discrepancies between the existing fonts that need to be resolved. (Specifically, Ome Bhatkhande English has a more standard character width for all characters, even the missing ones, which Hindi and Punjabi do not.) I'll need to resolve that first before the new pipeline is ready.

Additionally, I'm giving a talk on these fonts at Banasthali University on August 11th, so am focused on preparing that. I had hoped to get this font in before that symposium, so we could debut it there, but I do not have enough time to do so.

I will be back home later in August. Thanks for sharing your ideal deadline of August end. I'll see if I can think of a way to get this in before then, even if it means skipping the new build pipeline for now. Will keep you posted.

Thanks for your patience on this.

**Comment by rajadain** [comment]
Back and working on this again. Sorry to miss your August end deadline, but hope to make solid progress on this in early September. Just put up #69 for the build pipeline. Once that is in, will focus on getting Bangla in next.

**Comment by jain-sanjay** [comment]
Thank you Terence. My Guru's Birthday is on 10th September. If at all it is
possible to release by that date- it would be great

**Comment by rajadain** [comment]
Hi Sanjay,

I was able to spend some time on this tonight, and have made some progress:

image

Here's some questions I'd like answers for:

1. How do the characters look? Do they look right?
2. Are the characters vertically aligned as they should be?
3. Do the numbers look alright?
4. From what I can tell, we are using the Bangla equivalent of न instead of नी. Is that customary or just what you were able to do in your font? Can you tell me what the Bangla equivalent of नी looks like?
5. You used र instead of रे for the note, but that confuses it with the र of the stroke. Can you tell me what the Bangla equivalent of रे is?
6. Can you tell me what the Bangla equivalent of `da` and `ra` are? Do they work like Hindi? `dir` too?

**Comment by jain-sanjay** [comment]
Hi Terence

Thank you for your work on this, here are my answers

1. Characters look good.
2. yes- vertical alignment is good.
3. yes, numbers are okay
4. want to use न  for Ni.
5. Re note= রে
Ra Stroke = রা
da stroke = দা
dir stroke= দির

Hope this answers your questions. Please let me know if anything else is
needed from my side.

Thank you,

Sanjay Jian

**Comment by rajadain** [comment]
Hi Sanjay,

Please take a look at OmeBhatkhandeBangla here and let me know how it works: [omenad-fonts-3.0.0-beta.zip](https://github.com/user-attachments/files/16919925/omenad-fonts-3.0.0-beta.zip). I ended up re-sourcing the glyphs from the source AkaashNormal font to ensure vertical cadence between the glyphs, and balanced the horizontal spacing.

One difference from your recommendation is नी, which is the flavor I used in Bangla as well, since that matches the Hindi and the Punjabi versions.

Please let me know what you think and if you would recommend any changes.

Thanks.

**Comment by jain-sanjay** [comment]
This is indeed awesome! Thank you so much Terence, for making this happen.
I am very excited to use it

**Comment by jain-sanjay** [comment]
Just one quick question- did you incorporate the Chikari Symbol in this
version?

**Comment by rajadain** [comment]
No, that will be addressed in #64.

**Comment by rajadain** [comment]
This work was done in #71. Thanks for your contribution!

**Comment by jain-sanjay** [comment]
I wanted to provide the feedback, that Omenad Bangla is working great for
us.
Thank you once again for releasing it and integrating with the existing
fonts for compatibility.

Wanted to check if there is any update on adding Chikari character to the
Fonts.

Best,

-Sanjay

**Pull request closed without merging**
