### PR TITLE
Add Punjabi Font based on GurbaniLipi Font

### LINKED ISSUE #12: Adding Support for Punajbi Font (For Gurmat Sangeet)
Can you add the Punjabi font? As I want to write notations in Punajbi for Gurmat Sangeet and North India music.

I can help you with the Punjabi font creation. It will be very similar to Hindi Font.

### PR DESCRIPTION
**Pull request by mbaljeetsingh**
Added punjabi font based on GurbaniLipi Punjabi Font. Let me know if it looks it. Looking forward.

Closes #12

### CODE REVIEW

**Comment by rajadain** [comment]
Hi @mbaljeetsingh, Happy New Year! Thank you for putting this up. I'm traveling this week, but should have a chance next week to spend some time looking at this. We'll want to also copy the documentation to make a page for the Punjabi version once the font itself is ready.

**Comment by mbaljeetsingh** [comment]
Hi @rajadain, Happy New Year to you too. Sure, You can have a look at it once you get time. I'll work on the documentation part. Thanks.

**Comment by rajadain** [comment]
Hi Baljeet,

Back from the travels and finally got some time for this. I did some initial validation via FontForge and ironed out some basic issues. I pushed up my work in a branch and you can see the diff here: https://github.com/mbaljeetsingh/fonts/compare/master...omenad:mbaljeetsingh-master.

When comparing the Punjabi file against the Hindi file as a baseline I'm seeing some differences that I don't understand just yet, such as different values for `BeginChars` and `Encoding` for almost every character. I'll have to read up a bit on the SFD file format to learn what that means exactly.

Also, I see the Mizrab-ke-bol glyphs are missing. Were planning on adding those or going without them?

**Comment by mbaljeetsingh** [comment]
Hi @rajadain 

I'm not sure about it, you can have a look.
> When comparing the Punjabi file against the Hindi file as a baseline I'm seeing some differences that I don't understand just yet, such as different values for BeginChars and Encoding for almost every character. I'll have to read up a bit on the SFD file format to learn what that means exactly.

I was actually planning to go without Mizarab-ke-bol. I can add it similar to the one for the hindi font. I tried searching them for gurmat sangeet, but didn't find anything. That's why didn't add.

**Comment by mbaljeetsingh** [comment]
I also tried generating `.ttf` font for the punjabi. It seems to work similar to the other fonts (english, hindi) on my machine.

**Comment by mbaljeetsingh** [comment]
Hi @rajadain,

I have updated the `n`, can you see if it looks ok now?

> Remove non-integral values for shapes, add missing
extremities, ensure there are no self-intersecting
shapes, and generally validate the font.

I'm not sure, if I understand this. Can you guide me through it?

If possible, can you make the necessary modifications?

**Comment by rajadain** [comment]
> I can add it similar to the one for the hindi font.

For consistency, I'd like for them to be there. If you can do a Punjabi version of them that'd be great, otherwise we could keep the Hindi ones.

I'll add an explanation for the font validation that was done soon. I did make the modifications in that pull-request, and will do so in the future as well.

**Comment by mbaljeetsingh** [comment]
Hi @rajadain 

I have updated the `Mizrab-ke-bol` with the punjabi version. Please have a look.

**Comment by mbaljeetsingh** [comment]
Hi @rajadain 

Can you please share, how can I test the documetation on my local machine? I'm assuming everything is inside the docs directory.

**Comment by rajadain** [comment]
Hi @mbaljeetsingh,

The documentation is generated using [Jekyll](https://jekyllrb.com/), which runs on Ruby. You can install it using:

```console
$ gem install bundler jekyll
```

I just updated the dependencies on `master` in https://github.com/omenad/fonts/commit/3c0720c03ba6d90413bcbce7a245c668a4b7548a, an opened a PR against your work here: https://github.com/mbaljeetsingh/fonts/pull/2 that copies those updates.

Once those updates are in, go in to the `./docs/` directory and run:

```console
$ bundle install
```

to install the dependencies. Then you can run the documentation by running

```console
$ ./scripts/server.sh
```

in the root of the project.

Let me know if there's any questions. I'll get back to the fonts shortly.

Thanks for all your work on this!

**Comment by mbaljeetsingh** [comment]
Hi @rajadain 

I have done the first two steps
```
$ gem install bundler jekyll
$ bundle install
```

but I'm not able to run `server.sh` inside `windows`.
Any suggestions?

**Comment by mbaljeetsingh** [comment]
Tried `scripts/server` command, 
Now I'm getting the following error
image

**Comment by mbaljeetsingh** [comment]
Added `gem "faraday", "< 1.0"` inside docs/Gemfile. It seems to be working now

**Comment by rajadain** [comment]
Hi Baljeet,

Thanks for all your work on this. I think updating the Gemfile is something we should leave out, although I understand that you had to make some adjustments to get it to work under Windows, and that's fair. I think I'll have a separate effort to move the documentation to either Docker or Hugo or something that doesn't have as much of the Ruby dependency nightmare.

But the documentation is just a side thing, the main thing is the font. I'll take another look at it in a couple days and make a PR against your branch with any cleanups that result.

Thanks for your patience.

**Comment by rajadain** [comment]
Hi Baljeet,

When I got some time last week I tried to set the docs to generate via Docker in [this branch](https://github.com/omenad/fonts/tree/docs/docker), but haven't yet tested this on Windows yet (learning how to thread Docker through WSL is tricky).

In any case, I can probably handle the docs part myself. I'll get back to looking at the font itself soon.

Thanks.
Terence

**Comment by mbaljeetsingh** [comment]
Hi @rajadain 
Have you been able to look at it?

**Comment by rajadain** [comment]
Hi Baljeet,

Sorry, this has been a crazy week at work. I'll get back to this soon. I did take an initial look, and was trying to resolve some discrepancies around Ni, which seemed to be taking more width than it does in the other fonts. Dir was also taking more than twice the width. It's possible we may have to scale down all the characters to keep it consistent with the other Bhatkhande fonts. As I was investigating that this week FontForge kept crashing. I'll get back to it soon.

Thanks for your patience.

**Comment by rajadain** [comment]
While I'm still figuring out the differences, perhaps you can use the font at the current version: [OmeBhatkhandePunjabi.ttf.zip](https://github.com/omenad/fonts/files/4211079/OmeBhatkhandePunjabi.ttf.zip)

This was built using the following command:

```console
$ fontforge scripts/convert.pe bhatkhande/punjabi/OmeBhatkhandePunjabi.sfd 
```

**Comment by mbaljeetsingh** [comment]
> While I'm still figuring out the differences, perhaps you can use the font at the current version: [OmeBhatkhandePunjabi.ttf.zip](https://github.com/omenad/fonts/files/4211079/OmeBhatkhandePunjabi.ttf.zip)
> 
> This was built using the following command:
> 
> ```
> $ fontforge scripts/convert.pe bhatkhande/punjabi/OmeBhatkhandePunjabi.sfd 
> ```

Hi @rajadain 

Can you confirm If you have changed the **font name**? when I open the ttf it shows the name Ome Bhatkhande Hindi. I guess it needs to be changed to Ome Bhatkhande Punjabi. 

Looking forward to see it added to the web version soon.

**Comment by rajadain** [comment]
Ah good catch, added it in https://github.com/omenad/fonts/commit/cf04e9742f9ea4943de19a7edeac0c6fa7dcbc8e. Here's the updated version, if you could test again with it: [OmeBhatkhandePunjabi.ttf.zip](https://github.com/omenad/fonts/files/4211884/OmeBhatkhandePunjabi.ttf.zip)

**Comment by mbaljeetsingh** [comment]
Yeah, It seems to working fine now.

**Comment by rajadain** [comment]
Hi Baljeet,

I just compared the Punjabi version with the Hindi version in code, and made some edits to bring them more in line with each other in https://github.com/omenad/fonts/commit/0ff602a76d53c923c9442f6b7cdc0c255c79e8f6. Here's the latest font from that version: [OmeBhatkhandePunjabi.ttf.zip](https://github.com/omenad/fonts/files/4238700/OmeBhatkhandePunjabi.ttf.zip). Please take a look when you can. 

I still need to figure out some width issues before finalizing this, but we're getting really close!

**Comment by rajadain** [comment]
Hi Baljeet,

I just made https://github.com/mbaljeetsingh/fonts/pull/3 for the final changes to the font. I also retargeted this PR to a new branch `font/bhatkhande-punjabi`. Once approved, let's get your changes merged there, where I will do some more cleanup (with the docs, etc) and will then merge that into `master`.

Thanks.

**Comment by mbaljeetsingh** [comment]
Hi @rajadain,

I have merged the pull request. Yeah, Looking very good in the FontGoogles image. So, If I have to make any change, I'll make the PR to `font/bhatkhande-punjabi`, right. Are there any other changes required from my side?

**Comment by rajadain** [comment]
Excellent, thank you! No more changes required from your end. I'm now going to merge this PR (I've already changed it to target `font/bhatkhande-punjabi` instead of `master`), and then will do some cleanup. Then will create a release and let you know when it is publicly available. Thanks for all your work on this!! 👏

**Pull request merged**
