### PR TITLE
Add Kan superscript characters within the font

### PR DESCRIPTION
**Pull request by kristofb**
Add kan character for SRGMPDN + komal RGDN + teevra M, to ease writing musical phrases using Kan without depending on the capability of superscript.
I updated the docs also, so you can see how to write it. Any comment ?
Thanks

### CODE REVIEW

**Comment by rajadain** [comment]
Very impressive 👏 I really appreciate the clean commits, help reviewing this greatly!

I will take a look in the next few days and get back to you.

**Comment by rajadain** [comment]
What version of FontForge did you compile this for? When I run `./scripts/build` it doesn't recognize SFD v3.2. Trying to find a more modern Docker image to run this off of:

```
./scripts/build

Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 21:22 UTC 12-Jun-2015-ML-D.
 Based on source from git with hash: 99da6faa1ea3b4f80ecd333f596ea7dab205325e
Bad SFD Version number 3.2
Couldn't find a font file named /home/fontdev/swarlipi/OmeSwarlipi.sfd
OmeSwarlipi.sfd is not in a known format (or uses features of that format fontforge does not support, or is so badly corrupted as to be unreadable)
Open: Failed to open: ./swarlipi/OmeSwarlipi.sfd
Called from...
 ./scripts/convert.pe: line 21
```

**Comment by rajadain** [comment]
Just trying this out.

There are two issues with this approach:

## Unintuitiveness

Because the superscript letters are using different keys that don't match the notes, it breaks the intuitiveness of the font. Instead of using <kbd>r</kbd> for _Re_, this uses <kbd>c</kbd>, which must be learned and memorized separately.

## Only Notes

The superscript works for notes, but does not work for any modifiers. What if we want to denote the upper octave or the lower one? Those look incorrect:

image

In the above example, the dot below the Kan note should be much higher.

---

I suspect the true solution here may be to use [ligatures](https://en.wikipedia.org/wiki/Ligature_(writing)), with <kbd>k</kbd> being the modifier letter. The issue with ligatures is that we'd need one for every combination: `sk`, `suk`, `slk`, `sUk`, `sLk` for _Sa_, and so on for all the notes.

It is possible that we may run into other issues with ligatures, but I cannot think that far right now.

I have never done ligatures before, but I assume that FontForge has support for it.

There may also be a programmatic way to generate ligatures for all the combinations listed above via some sort of scripting, but I am not familiar enough to do that.

---

Thank you for your thoughtful contribution, but this is not ready to be merged into the official repository. Please feel free to use your variant in your projects.

Should I make any progress on the matter, I will report so here.

**Comment by kristofb** [comment]
Hi, ok, I'll think about it. Concerning the octave dot markers, we may consider the question differently : Should we add them or consider them as implicitly related to the main following note for the reader? <R>S' => R is above S' so it's R' in fact,  <N>S' => N is below S'. For larger intervals, they may be regulated by the raga aaroha and avaroha rules, so it still can be implicit.

Concerning the intuitiveness of the font, it's true it's not easy, but, I'm thinking of a different writing, with a simple converter which could be released as associated source code :

```S M, M <G> P, [ S' D] N S'```  ==> ```sm,mfp,qsuednsu```

```S' N D P, m P D n D P, (mP) (DP) M <M>R S```  ==> ```sundp,MpdNdp,@Mp@dpmhrs```

image

**Pull request closed without merging**
